apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
  name: disable-hpa-1-replica-only-9652a736
data:
  DD_ENV: prod
  DD_LOGS: '[{"source":"k8s", "service":"disable-hpa-1-replica-only", "version":"alpine3.22-perl"}]'
  DD_SERVICE: disable-hpa-1-replica-only
  DD_VERSION: alpine3.22-perl
  LOG_LEVEL: info
  PORT: '8080'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
  name: disable-hpa-1-replica-only
spec:
  template:
    metadata:
      annotations:
        fnatt.io/inject-ca-bundle: enabled
        fnatt.io/inject-ca-env: enabled
      labels:
        team: demoteam
        app: disable-hpa-1-replica-only
        env: prod
    spec:
      securityContext: {}
      containers:
      - image: nginxinc/nginx-unprivileged:alpine3.22-perl
        resources:
          requests:
            cpu: '0.5'
            memory: 512Mi
          limits:
            cpu: '2'
            memory: 2Gi
        securityContext: {}
        ports:
        - containerPort: 8080
        name: main
        envFrom:
        - configMapRef:
            name: disable-hpa-1-replica-only-9652a736
  replicas: 1
  selector:
    matchLabels:
      team: demoteam
      app: disable-hpa-1-replica-only
      env: prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
  name: disable-hpa-1-replica-only
spec:
  ingressClassName: ingress-nginx-pm
  rules:
  - host: disable-hpa-1-replica-only.prod.fnatt.no
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 80
            name: disable-hpa-1-replica-only
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
  name: disable-hpa-1-replica-only
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
  selector:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: disable-hpa-1-replica-only
    env: prod
    team: demoteam
  name: disable-hpa-1-replica-only
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: disable-hpa-1-replica-only
      env: prod
      team: demoteam
