apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app-c8a8d279
data:
  DD_ENV: acc
  DD_LOGS: '[{"source":"k8s", "service":"public-app", "version":"alpine3.22-perl"}]'
  DD_SERVICE: public-app
  DD_VERSION: alpine3.22-perl
  LOG_LEVEL: info
  PORT: '8080'
  TZ: Europe/Oslo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app
spec:
  template:
    metadata:
      annotations:
        fnatt.io/inject-ca-bundle: enabled
        fnatt.io/inject-ca-env: enabled
      labels:
        team: demoteam
        app: public-app
        env: acc
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: nginxinc/nginx-unprivileged:alpine3.22-perl
        resources:
          requests:
            cpu: '0.5'
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        name: main
        envFrom:
        - configMapRef:
            name: public-app-c8a8d279
  selector:
    matchLabels:
      team: demoteam
      app: public-app
      env: acc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app
spec:
  ingressClassName: ingress-nginx-pm
  rules:
  - host: public-app.acc.fnatt.no
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 80
            name: public-app
        pathType: Prefix
  - host: my-interal-ingress.polarismedia.no
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 80
            name: public-app
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
  selector:
    app: public-app
    env: acc
    team: demoteam
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: public-app
      env: acc
      team: demoteam
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: public-app
    env: acc
    team: demoteam
  name: public-app
spec:
  maxReplicas: 4
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-app
