name: Setup kubeconform
description: Checks for kubeconform and installs if missing
runs:
  using: composite
  steps:
    - name: Check kubeconform presence
      id: kubeconform-check
      shell: bash
      run: |
        if command -v kubeconform >/dev/null 2>&1; then
          echo "kubeconform is already installed."
          echo "installed=true" >> "$GITHUB_OUTPUT"
        else
          echo "kubeconform is not installed."
          echo "installed=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Install kubeconform
      if: steps.kubeconform-check.outputs.installed == 'false'
      shell: bash
      run: |
        curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz
        tar -xzf kubeconform.tar.gz
        sudo mv kubeconform /usr/local/bin/kubeconform
        sudo chmod +x /usr/local/bin/kubeconform
