apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets-88cd5ed2
data:
  DD_ENV: prod
  DD_LOGS: '[{"source":"k8s", "service":"app-with-secrets", "version":"alpine3.22-perl"}]'
  DD_SERVICE: app-with-secrets
  DD_VERSION: alpine3.22-perl
  LOG_LEVEL: info
  PORT: '8080'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets
spec:
  template:
    metadata:
      annotations:
        fnatt.io/inject-ca-bundle: enabled
        fnatt.io/inject-ca-env: enabled
      labels:
        team: demoteam
        app: app-with-secrets
        env: prod
    spec:
      securityContext: {}
      containers:
      - image: nginxinc/nginx-unprivileged:alpine3.22-perl
        resources:
          requests:
            cpu: '0.5'
            memory: 512Mi
          limits:
            cpu: '2'
            memory: 2Gi
        securityContext: {}
        ports:
        - containerPort: 8080
        name: main
        envFrom:
        - secretRef:
            name: accessdatabase-prod
        - secretRef:
            name: topsecrets-prod
        - secretRef:
            name: shared-secret
        - secretRef:
            name: very-very-specific-secret
        - configMapRef:
            name: app-with-secrets-88cd5ed2
  selector:
    matchLabels:
      team: demoteam
      app: app-with-secrets
      env: prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets
spec:
  ingressClassName: ingress-nginx-pm
  rules:
  - host: app-with-secrets.prod.fnatt.no
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 80
            name: app-with-secrets
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
  selector:
    app: app-with-secrets
    env: prod
    team: demoteam
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: app-with-secrets
      env: prod
      team: demoteam
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: app-with-secrets
spec:
  maxReplicas: 8
  minReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-with-secrets
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: 'true'
    argocd.argoproj.io/hook: PreSync
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: accessdatabase-prod
spec:
  itemPath: vaults/example/items/accessdatabaseprod
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: 'true'
    argocd.argoproj.io/hook: PreSync
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: topsecrets-prod
spec:
  itemPath: vaults/example/items/topsecretsprod
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: 'true'
    argocd.argoproj.io/hook: PreSync
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: shared-secret
spec:
  itemPath: vaults/example/items/shared-secret
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: 'true'
    argocd.argoproj.io/hook: PreSync
  labels:
    app: app-with-secrets
    env: prod
    team: demoteam
  name: very-very-specific-secret
spec:
  itemPath: vaults/example/items/very-very-specific-secret
